### ISSUE TITLE
독후감 등록시 독후감 내용 긴 경우 등록 안되는 문제 수정

### ISSUE THREAD

**Issue by geneaky** [geneaky/BookChat#329]

**Comment by Kova700** [comment]
독후감 content가 긴 경우 등록이 잘 되나,
title이 긴 경우 
400  {"errorCode":"500","message":"예상치 못한 예외가 발생했습니다."}
이 넘어오는 현상이 아직 해결되지 않음

**Comment by geneaky** [comment]
이거는 title 길이 제한을 거는게 좋을거같습니다 한 100자 정도 제한두는게 어때요?

**Comment by Kova700** [comment]
title과 content에  길이 제한을 거는 것은 충분히 가능한데 따로 이유가 있을까요?
