### ISSUE TITLE
사용자 회원가입 중 회원가입은 성공했지만 로그인 요청 시 404 에러가 발생하는 현상

### ISSUE THREAD

**Issue by Kova700** [geneaky/BookChat#337]
errorCode : "4040100" message : "사용자를 찾을 수 없습니다. " 가 넘어오는 현상이 있음
(유저 이미지 관련 오류 일 수도 있다 생각함)
![image](https://github.com/geneaky/BookChat/assets/81726145/cbf03c8d-3de5-4c8d-bda8-6ddcac9df628)
![image](https://github.com/geneaky/BookChat/assets/81726145/28ea85ef-713b-4d95-aca3-44fce55a01a9)

**Comment by geneaky** [comment]
이거 전에 사용자 회원탈퇴 soft delete하면서 status 컬럼이 db user table에 추가되었는데
회원가입시에 신규 계정 생성 로직에 status 넣어주는 부분이 빠져있었습니다
운영 db 계정에 상태 정보 업뎃 해두었슴다
