### ISSUE TITLE
방장이 채팅방 퇴장 시, 채팅방이 soft 삭제되나, 소켓 연결이 되는 현상이 있

### ISSUE THREAD

**Issue by Kova700** [geneaky/BookChat#339]
클라이언트 단에서 연결이 안되게 막아두긴 했지만 
서버 단에서도 막아두는게 좋다고 생각됨
(자의적 판단으로 선택하시면 될듯)

**Comment by geneaky** [comment]
해당 케이스 반영했습니다
웹소켓 커넥션 자체는 저희 회원이라면 서버와 커넥션 연결은 가능하되 채팅방 참여자가 아닌경우, 존재하지 않는 채팅방인 경우에 subscribe를 시도할때 연결이 불가능하도록 처리했습니다
