### ISSUE TITLE
채팅방 인원이 방장 혼자 있는 채팅방에서 나가기를 누른 후, 채팅방을 쿼리하면 해당 채팅방이 넘어오는 현상

### ISSUE THREAD

**Issue by Kova700** [geneaky/BookChat#340]
채팅방 인원이 방장 혼자 있는 채팅방에서 나가기를 누르면 방장이 나갔다고 채팅방이 터졌다고 메세지가 날라오긴함
But, 다시 채팅방 목록에서 채팅방을 쿼리하면 해당 채팅방이 넘어오고 있음
이런 경우에는 남은 유저가 없으니까 그냥 soft 삭제가 아닌 그냥 삭제가 되어야 할 거 같음

**Comment by Kova700** [comment]
soft와 hard를 중첩해서 사용하기 보단 하나로 사용하는 것이 좋겠다는 의견에 
회의 결과 soft 삭제는 유지하되, 서버 측에서 채팅방 목록 쿼리 시 
"클라이언트가 방장이고.,채팅방이 isExpolded == true" 라면 필터링 해서 쿼리 목록에서 제외해서 주는 방향으로 결정

클라이언트 단에서도 쿼리 받은 데이터가 "내가 방장이고, 채팅방이 isExpolded == true" 라면
DB에 저장하지 않고 UI에도 노출 시키지 않는 방향으로 구현 예정

추가적으로는 soft 삭제 중인 채팅방이지만 
해당 채팅방에서 방장이 아닌 부방장을 포함한 일반 유저들은
채팅방 나가기 API를 호출하면 서버 DB에 반영이되어 
다음 쿼리에는 해당 채팅방이 쿼리 결과에 담겨있지 않았으면 함 (현재 그렇게 되어있음 ㅇㅇ)

그리고  
soft 삭제 기간이 만료되어 서버 DB에 해당 채팅방이 존재하지 않을 때,
채팅방 정보 조회 API, 채팅방 나가기 API를 클라이언트가 호출한다면 404에러 혹은 존재 하지 않는
채팅방임을 알 수 있는 Flag를 던져줬으면 함
(이유 : soft 삭제를 채택한 이유와 마찬가지로 소켓을 통해 채팅방 폭발 유무를 알지 못한 유저가
soft 삭제가 만료되어 서버에 조차 해당 데이터가 없어 쿼리 시에도 폭발 유무 데이터가 넘어오지 않는다면,
사용자는 그냥 해당 채팅방의 상태를 알 수가 없이 소켓 연결, 채팅 쿼리를 지속적으로 요청하는 상황이 생김)

**Comment by geneaky** [comment]
이거는 내가 방장이고, 채팅방이 isExpolded == true 요 조건으로 진행하려하는데
아직 soft 삭제 기간에 따른 스케쥴링으로 hard 삭제 처리는 구현되어 있지 않아서 이거는 이슈 분리해서 등록해주시면 나중에 hard delete 스케쥴러 구현할때 추가하겠습니다

**Comment by Kova700** [comment]
#346 에 이어서 분리 작성 했습니닷👍

**Comment by Kova700** [comment]
해당 이슈에 대한 종합 이슈 발생으로인해
- #348 

로 이전
