### ISSUE TITLE
채팅방 정보 수정 API 호출 시 errorCode : "500" message : "예상치 못한 예외가 발생했습니다" 가 넘어오는 현상

### ISSUE THREAD

**Issue by Kova700** [geneaky/BookChat#343]
채팅방 정보 수정 API 호출 시 errorCode : "500" message : "예상치 못한 예외가 발생했습니다" 가 넘어오는 현상이 있음
![image](https://github.com/geneaky/BookChat/assets/81726145/db4466ed-ee98-4714-9c54-1b4eb961809d)

**Comment by geneaky** [comment]
이거 위에 요청 방식보니까 application/json으로 요청하셨는데
![image](https://github.com/geneaky/BookChat/assets/53224348/49da1315-bd46-4678-948a-30d1f8f581e3)
이미지 처럼 mutlipart/form으로 해주셔야합니다

**Comment by Kova700** [comment]
말해주신 내용대로 확인해본 결과 
전송 시에 mutlipart/form 부분과 application/json이 같이 전송되고 있습니다.
유저 프로필 수정API도 똑같은 형태로 전송되고 있으나 잘 작동되고 있는걸로 보아
현재 API쪽에 문제가 있지 않을까 생각이 됩니다..
(늦게 답장드려 죄송합니닷..)

![image](https://github.com/user-attachments/assets/2cf924e5-ff59-47af-b4b1-31a4caab2217)
![image](https://github.com/user-attachments/assets/e11fc5e5-bbe1-4cd9-9eda-2bfb165b0c87)

**Comment by geneaky** [comment]
![image](https://github.com/user-attachments/assets/8b46b3e9-c391-4dd8-bb75-400b6933be19)
병국씨 이거 제가 테스트할때는 동작하는데 다시 한 번 확인 가능하실까욥?
