### ISSUE TITLE
강퇴당한 유저가 채팅방 정보조회 API 호출 시 강퇴 유무를 알 수 없음

### ISSUE THREAD

**Issue by Kova700** [geneaky/BookChat#344]
채팅방에서 강퇴당한 유저가 채팅방 정보조회 API를 호출한다면 
404 {"errorCode":"4040500","message":"참여자를 찾을 수 없습니다."}가 넘어오는 현상이 있음

만약 강퇴된 유저 목록을 서버에서 유지해서 가지고 있다면 
채팅방 정보조회를 요청하는 클라이언트가 강퇴목록에 포함되어있다면 
채팅방 정보를 넘겨주는 방향 ("isBanned":true) 으로 수정해주길 희망함
아니면 특정 에러코드를 넘겨주거나..  

![image](https://github.com/geneaky/BookChat/assets/81726145/cb5221b8-14c5-4eec-9d2e-579a5c84644a)

소켓에 연결되어있지 않던 유저가 채팅방에서 강퇴되었을 경우
유저는 채팅방에서 강퇴된 유무를 알 수 없음
+ 강퇴된 유저는 사용자 채팅방 목록 쿼리시 강퇴된 채팅방은 넘어오지 않는데,
이런경우 사용자는 강퇴유무를 인지 하지 못하고 목록에서 해당 채팅방이 사라지는 현상이 생김
+ 로컬 데이터에 남아있는 채팅방을 누르면 채팅방 정보 조회를 호출한뒤 강퇴 당했다면
강퇴 당한 UI를 보여주는 게 좋은 방법이라 생각되어 해당 이슈를 남김

전체 채팅방 조회에서 강퇴 되었던 채팅방을 검색하면 
강퇴 유무가 잘 나오고 있긴함
![image](https://github.com/geneaky/BookChat/assets/81726145/08000dd1-84c0-4051-bdd8-c5e87f6f1d51)

**Comment by geneaky** [comment]
요거는 서버에서 강퇴된 사용자에 대한 정보를 알고있어서 isBanned 응답 추가하겠습니다

**Comment by Kova700** [comment]
> 요거는 서버에서 강퇴된 사용자에 대한 정보를 알고있어서 isBanned 응답 추가하겠습니다

isBanned 필드가 이미 존재하는데 강퇴 당한 유저가 채팅방 정보조회 API를 호출하면 isBanned  = true로 넘어오는게 아니라 위에 사진처럼 404가 넘어오는 상황입니다잇

**Comment by Kova700** [comment]
해당 이슈에 대한 종합 이슈 발생으로인해

채팅방 삭제 정책 soft delete -> hard delete로 수정  #348
로 이전
