### ISSUE TITLE
채팅방 삭제 정책 soft delete -> hard delete로 수정 

### ISSUE THREAD

**Issue by Kova700** [geneaky/BookChat#348]
# 부연 설명 (히스토리)
기존 채팅방 삭제 정책은 soft delete 였음
> 이유 :  현재 채팅방 삭제에 대한 이벤트는 오로지 소켓 연결 중에만 받을 수 있음,
서버에서 채팅방을 hard delete로 삭제하면 "채팅방 삭제 소켓 이벤트"를 받지 못한 유저는 
사용자 채팅방 목록 조회 시 해당 채팅방이 쿼리 결과에 존재하지 않기 때문에 (이미 삭제되고 없기 때문)
채팅방 삭제 사실을 인지하지 못한 상태에서 채팅방 목록에서 해당 채팅방이 사라지는 현상이 생김
이런 현상을 막기 위해서 특정 기간동안 채팅방이 방장에 의해 삭제되었더라도, 
사용자 채팅방 조회 쿼리 시, 삭제된 채팅방도 쿼리에 포함시켜서 받는 구조로 해결하고자 했었음 (soft delete)

하지만
- #340   

이슈가 생겼지만 불필요한 채팅방 데이터의 경우 서버에서 필터링해서 클라이언트에게 
넘겨주는 방향으로 해결할 수 있었음.

문제는 
- #344 

이슈를 해결하는 중,
강퇴당한 유저가 채팅방 정보조회 API 호출을 가능하게 하는 게
굳이 노출되지 않아도 되는 불필요한 정보 노출이 발생한다고 판단, 

그래서 굳이 soft delete에 대한 전반적인 문제들을 해결하기보단
hard delete 방식을 채택하고, 가장 근원적인 문제인 
> 클라이언트가 채팅방의 상태를 알지 못하고 채팅방 목록에서 채팅방이 사라지는 문제  

를 해결해보고자 했음

</br>

# 새로운 해결책 
채팅방 삭제 정책을 hard delete로 수정하고,
> 클라이언트가  채팅방 정보 조회 API를 요청하거나 채팅방 나가기 API를 요청했을 때,
이미 강퇴당한 유저이거나, 이미 폭파되어 서버상에 존재하지 않는 채팅방인 경우에 대하여 
특정 status code라던지 커스텀 에러코드를 사용하여 현재 유저가 요청한 채팅방에 대한 
로컬 데이터 상태를 업데이트 하는 방식

을 채택

예를 들면
채팅방 정보 조회 혹은 채팅방 나가기 API를 호출했을 때
해당 요청을 보낸 유저가 이미 강퇴된 유저라면
403 코드 혹은 커스텀 에러 코드를 응답 헤더에 넣어주고,

해당 요청을 보냈지만, 해당 채팅방이 존재하지 않는 채팅방이거나 이미 존재하지 않는 채팅방인경우
404 코드 혹은 커스텀 에러 코드를 응답 헤더에 넣어주는 방식이다.

하지만 
- #344 

이슈에 이미 강퇴 당한 유저가 채팅방 정보 조회 API를 호출하면 404 코드가 넘어오고 있는걸로보아
채팅방이 존재하지 않는 경우와 채팅방 참여자가 존재하지 않는경우에 대해서 코드 구분이 필요해 보임

추가적으로 채팅방 나가기 API의 경우
이미 강퇴되었거나, 채팅방이 존재하지 않아서 실패하는 경우를 단순히 나가기 API 요청이 실패한 경우와 구분하고자해서
채팅방 정보 조회의 경우와 마찬가지로 구분이 필요하다고 생각했음
(클라이언트가 이미 해당 채팅방이 삭제(폭파)되었거나 해당 채팅방에서 강퇴되었음을 알고 로컬 데이터가 해당 상태로 업데이트 
되어있다면 API를 호출하지 않지만, 해당 상태가 업데이트 되어있지 않은 경우 어쩔 수 없이 API를 호출해야하기 때문)

이렇게 된다면
기존에 
- #332 
- #331

이슈에 추가된
isBanned, isExploded 필드가 필요가 사라지기 때문에 수정이 필요함

- #333 

이슈에도 isBanned 필드의 필요가 사라짐
isEntered 필드 또한 실시간 채팅방 상태가 반영이 안되는 이슈가 있어서 필요성이 사라져버림

# 결론
- [x] 사용자 채팅방 조회 API에 필드에 isBanned, isExploded가 제거가 필요함
- [x] 채팅방 정보 조회 API에 필드에 isBanned, isExploded가 제거 되고,  isBanned, isExploded(존재하지 않음)  상황에 맞는 실패 응답 코드가 반환되게 수정되어야함
- [x] 채팅방 나가기 API의 실패 응답코드를 이미 해당 유저가 존재하지 않거나, 채팅방이 존재하지 않는 경우에 대한 구분 되는 실패 응답코드가 반환되게 수정되어야함
- [x] 전체 채팅방 조회 API에 isEntered, isBanned가 제거가 필요함
- [x]  채팅방 입장 API에 대한 실패 응답으로 isEntered, isBanned, isExploded 상황에 맞는 실패 응답 코드가 반환되게 수정되어야함

추가적으로 FCM으로 채팅방 폭파, 채팅방 강퇴 이벤트를 받는 건 있으면 좋은 경우지만
FCM의 누락, 지연으로 인해 FCM만으로는 정상 운영이 불가능하기 때문에 위 작업들이 선행되어야 한다고 판단됨
(FCM으로 채팅방 폭파, 강퇴 이벤트를 받으면 굳이 서버에게 API를 요청해서 실패 응답을 받아서 상태 업데이트를 할 
필요가 사라지긴 해서 있으면 좋긴하지만, 없어도 문제는 되지 않는)

**Comment by geneaky** [comment]
FCM은 추후 정말 필요한 상황이 오면 그때 추가하는걸로 하죠~

**Comment by geneaky** [comment]
채팅방 정보 조회 에러 응답 케이스
- 강퇴 당한 경우
- 채팅방이 폭파된 경우
- 참여자을 찾을 수 없는 경우
로 추가했습니다

**Comment by geneaky** [comment]
채팅방 나가기 에러 응답 케이스
- 채팅방이 폭파된 경우 (4040400)
- 참여자을 찾을 수 없는 경우 (4040500)
로 추가했습니다
