### ISSUE TITLE
회원탈퇴 시, 탈퇴한 유저가 채팅방에 그대로 남아있는 현상이 있음

### ISSUE THREAD

**Issue by Kova700** [geneaky/BookChat#352]
사용자가 회원탈퇴를 한 상황에
다른 유저들이 채팅방을 보면 탈퇴한 유저가 그대로 남아있는 현상이 있음
(탈퇴시 채팅방에서 나가져야함과 동시에 ㅁㅁ님이 나갔음을 알 수있는 메세지가 채팅에 남아있어야한다고 생각됨)

추가적으로 탈퇴한 유저가 다시 재가입을 요청했을 때,
status Code : 400
{"errorCode":"4000100","message":"이미 가입된 사용자입니다."}
이 넘어오는 현상이 있음 (아마 soft delete때문이지 않을까 추측됨)
이에 관해 탈퇴 후 재가입 시도 시 정책 결정이 필요해보임
1. 특정 기간 동안 재가입을 막는다. (그렇다면 기간은 얼마나 잡을건지)
  - 만약 가입을 막는다면 400이 아닌 다른 응답 코드를 넘겨 받음으로써 특정 기간동안 가입이 불가능하다는 표시를 유저한테 보여주는게 좋다고 생각됨
2. 그냥 바로  새 계정으로 재가입을 가능하게 허용한다.
3. 기존에 soft 삭제 중인 계정을 다시 복구한다.

또한 탈퇴한 유저가 속해있던 채팅방에 새로운 메세지가 발생한 경우,
서비스 탈퇴를 했음에도 FCM메세지가 수신이 되고 있음

추가적으로 채팅방의 방장이 탈퇴를 진행했을때도, 
채팅방이 터지지 않고 유지되고, 
채팅방 유저 목록에 해당 방장이 그대로 남아있는 현상이 있음

### 체크리스트
- [ ] 탈퇴한 유저가 채팅방에 그대로 남아있는 현상
- [ ] 방장이 회원탈퇴를 하였을때, 채팅방이 그대로 남아있는 현상
- [ ] 탈퇴한 유저가 재가입 시도 시 정책 결정
- [ ] 탈퇴한 유저의 FCM 메세지 수신

**Comment by geneaky** [comment]
특정 기간 동안 재가입을 막을 이유는 딱히 없고, 
채팅방만 나가기 시키고 서재랑, 고민, 고민기록, 독후감은 남겨뒀다가 재가입시 다시 보여줄 수 있을거같아서 이거는 soft 삭제를 푸는게 좋을거 같네여

**Comment by Kova700** [comment]
방장이 탈퇴인경우
채팅방 폭발 + 방장 유저 데이터는 보존(특정 기간동안 재가입 시  채팅방 목록은 초기화된 채로 서재, 고민, 고민기록, 독후감은 보존)

그냥 유저 탈퇴인경우
채팅방 나가기 + 유저 데이터 보존(특정 기간동안 재가입 시  채팅방 목록은 초기화된 채로 서재, 고민, 고민기록, 독후감은 보존)
이 맞을까요?? 

데이터가 보존되는 특정 기간은 며칠로 잡는게 좋을까요?
