### ISSUE TITLE
고민 기록 등록 시 내용 긴 경우 등록 안되는 현상 

### ISSUE THREAD

**Issue by Kova700** [geneaky/BookChat#354]
AgonyRecord 생성 시, Content 혹은 title 내용이 엄청 길다면 400 넘어오는 현상이 있음
{"errorCode":"500","message":"예상치 못한 예외가 발생했습니다."}

고민 기록 수정시에는 길이를 길게 해도 문제가 안되는거보면
AgonyRecord 등록 API 측에 문제가 있다고 생각됨

**Comment by geneaky** [comment]
이것도 고민기록 최대 입력을 100자로 제한하는게 좋을거같습니다

**Comment by Kova700** [comment]
요놈도 충분히 가능하지만 혹시 따로 이유가 있을까요?
