### ISSUE TITLE
책 커버 이미지가 없는 응답의 경우 대체 이미지로 로딩 

### ISSUE THREAD

**Issue by geneaky** [geneaky/BookChat#63]

**Comment by Kova700** [comment]
![image](https://user-images.githubusercontent.com/81726145/177055969-053a7659-dee5-40d0-977c-2b53dee8a863.png)
![image](https://user-images.githubusercontent.com/81726145/177055976-399fa48c-614f-4ca9-8f36-042176c4932b.png)
